### ISSUE TITLE
具体应该安装什么包

### ISSUE THREAD

**Issue by feiandxs** [JAJA-zhong/Microsoft_Speech_Studio_Text-to-speech_API#1]
我看引用包是
`import azure.cognitiveservices.speech as speechsdk`

但实际上只这样安装还是缺少包

**Comment by JAJA-zhong** [comment]
这样是要到微软下载SDK包的。

**Comment by feiandxs** [comment]
可能我没有表述清楚，其实我是发现我只执行`pip install azure`并不行，不过后来我自己找到了。
还需要按照一个
`pip install azure-cognitiveservices-speech`

如果后来人看到的话可以按照我的安装命令少浪费几分钟了。
